# Site settings
title: MFMA
email: jbothma@gmail.com
description: 'This is a mobile- and search-engine friendly mirror of the original MFMA website (http://mfma.treasury.gov.za) with some additional third-party guidance material for the sole purpose of helping people find the fundamentally important resources available there. Please treat mfma.treasury.gov.za as the canonical and up to date source of MFMA information.'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mfmamirror.github.io"
twitter_username: jdbothma
github_username:  jbothma

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap