# Site settings
title: MFMA
email: jbothma@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mfmamirror.github.io"
twitter_username: jdbothma
github_username:  jbothma

# Build settings
markdown: kramdown
